name: Deploy GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  Deploy-GitHub-Pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "yarn"
      - run: yarn --frozen-lockfile
      - run: yarn run-s check clean:dist build
      - uses: crazy-max/ghaction-github-pages@v2
        if: ${{ success() }}
        with:
          target_branch: gh-pages
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
